#!/bin/bash
readonly DEFAULT_INCLUDE_DIRECTORY='include/*.h'
readonly DEFAULT_SRC_DIRECTORY='src/*.c'

export FILES_TO_INCLUDE="$DEFAULT_INCLUDE_DIRECTORY intro/$DEFAULT_INCLUDE_DIRECTORY"
export FILES_TO_COMPILE="intro/$DEFAULT_SRC_DIRECTORY"
