#!/bin/bash
export partsToBuild=(
    "gameStates"
    "runtime"
    "controls_t"
    "input"
    "FPS"
    "player_t"
    "object_t"
    "camera_t"
    "state_t"
    "animation_t"
    "boxes_t"
    "color_t"
    "settings_t"
    "window_t"
    "vsync"
    "config_t"
    "background_t"
    "HUD_t"
    "character_t"
    # "font_t"
    "asset_t"
    "watch_t"
    "log"
    "stdfunc"
)
export testsToBuild=(
    # "gameStates"
    # "runtime"
    "controls_t"
    "input"
    "FPS"
    # "player_t"
    "object_t"
    "camera_t"
    "state_t"
    "animation_t"
    "boxes_t"
    "color_t"
    "settings_t"
    "window_t"
    "vsync"
    # "config_t"
    # "background_t"
    # "HUD_t"
    # "character_t"
    # "font_t"
    "asset_t"
    # "watch_t"
    "log"
    "stdfunc"
)
export staticParts=(
    "inih"
    "plthook"
)
export rootSharedObjectName="root"

export executableMainPackage='main'
export testsMainPackage='test'
